# Generated by Django 2.2 on 2019-08-04 08:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0029_Direktverbindungen'),
    ]

    operations = [
        migrations.CreateModel(
            name='manuelle_Berechtigungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
