# Generated by Django 2.2 on 2019-08-04 08:42

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0030_manuelle_berechtigungen'),
    ]

    operations = [
        migrations.CreateModel(
            name='manuelle_Berechtigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('ersteller', models.CharField(max_length=50, null=True)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='manuelle_Berechtigungen',
        ),
    ]
