# Generated by Django 2.2 on 2019-08-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0031_auto_20190804_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuelle_berechtigung',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Manuell nachzuhaltenede Berechtigung', 'verbose_name_plural': '10_Manuell nachzuhaltenede Berechtigungen'},
        ),
        migrations.AddField(
            model_name='manuelle_berechtigung',
            name='verbundene_af',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rapp.TblAfliste'),
        ),
    ]
