# Generated by Django 2.2 on 2019-08-04 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0032_auto_20190804_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuelle_berechtigung',
            name='letzte_aenderung',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
