# Generated by Django 2.2 on 2019-08-08 17:28

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0034_auto_20190807_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuelle_berechtigung',
            name='relativ',
            field=mdeditor.fields.MDTextField(default=''),
        ),
        migrations.AlterField(
            model_name='manuelle_berechtigung',
            name='statisch',
            field=mdeditor.fields.MDTextField(default=''),
        ),
    ]
