# Generated by Django 2.2 on 2019-08-08 21:15

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0035_auto_20190808_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuelle_berechtigung',
            name='relativ',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='manuelle_berechtigung',
            name='statisch',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
