# Generated by Django 2.2.4 on 2019-09-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0036_auto_20190808_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblrollen',
            unique_together=set(),
        ),
    ]
