# Generated by Django 2.2.4 on 2019-09-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0037_auto_20190925_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblrollehataf',
            unique_together=set(),
        ),
    ]
