# Generated by Django 2.2.4 on 2019-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0038_auto_20190925_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserhatrolle',
            name='schwerpunkt_vertretung',
            field=models.CharField(blank=True, choices=[('Schwerpunkt', 'Schwerpunktaufgabe'), ('Vertretung', 'Vertretungstätigkeiten, Zweitsysteme'), ('Allgemein', 'Rollen, die nicht Systemen zugeordnet sind')], db_column='schwerpunkt_vertretung', max_length=100, null=True),
        ),
    ]
