# Generated by Django 2.2.4 on 2019-09-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0043_auto_20190925_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluebersichtafgfs',
            unique_together=set(),
        ),
    ]
