# Generated by Django 2.2.4 on 2019-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0046_auto_20190925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluseridundname',
            name='geloescht',
            field=models.IntegerField(blank=True, db_column='geloescht', null=True, verbose_name='gelöscht'),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='name',
            field=models.CharField(db_column='name', db_index=True, max_length=75),
        ),
        migrations.AlterIndexTogether(
            name='tbluseridundname',
            index_together={('geloescht', 'name', 'userid'), ('geloescht', 'zi_organisation')},
        ),
    ]
