# Generated by Django 2.2.4 on 2019-09-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0047_auto_20190925_1512'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tbluseridundname',
            index_together={('geloescht', 'zi_organisation')},
        ),
    ]
