# Generated by Django 2.2.4 on 2019-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0048_auto_20190925_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblorga',
            name='team',
            field=models.CharField(db_column='team', max_length=64),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='abteilung',
            field=models.CharField(db_column='abteilung', db_index=True, max_length=64),
        ),
    ]
