# Generated by Django 2.2.4 on 2019-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0049_auto_20190925_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblgesamt',
            options={'managed': True, 'verbose_name': 'Eintrag der Gesamttabelle (tblGesamt)', 'verbose_name_plural': '08_Gesamttabelle Übersicht (tblGesamt)'},
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='datum',
            field=models.DateTimeField(db_column='datum', verbose_name='Recht gefunden am'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='geaendert',
            field=models.IntegerField(blank=True, db_column='geaendert', null=True, verbose_name='AF geändert'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='gefunden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='letzte_aenderung',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='loeschdatum',
            field=models.DateTimeField(blank=True, db_column='loeschdatum', null=True, verbose_name='Löschdatum'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='neueaf',
            field=models.CharField(blank=True, db_column='neueaf', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='patchdatum',
            field=models.DateTimeField(blank=True, db_column='patchdatum', null=True),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='tf_eigentuemer_org',
            field=models.CharField(blank=True, db_column='tf_eigentuemer_org', max_length=64, null=True, verbose_name='TF-Eigentümer-orga'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='tf_kritikalitaet',
            field=models.CharField(blank=True, db_column='tf_kritikalitaet', max_length=64, null=True, verbose_name='TF-Kritikalität'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='wiedergefunden',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblplattform',
            name='tf_technische_plattform',
            field=models.CharField(db_column='tf_technische_plattform', max_length=32, unique=True, verbose_name='Plattform'),
        ),
    ]
