# Generated by Django 2.2.4 on 2019-09-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0050_auto_20190925_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblgesamt',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Eintrag der Gesamttabelle (tblGesamt)', 'verbose_name_plural': '08_Gesamttabelle Übersicht (tblGesamt)'},
        ),
    ]
