# Generated by Django 2.2.4 on 2019-09-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0052_auto_20190925_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblafliste',
            options={'managed': True, 'ordering': ['af_name'], 'verbose_name': 'Gültige AF', 'verbose_name_plural': '98_Übersicht gültiger AFen (tbl_AFListe)'},
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='angehaengt_bekannt',
            field=models.IntegerField(blank=True, db_column='angehaengt_bekannt', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='angehaengt_sonst',
            field=models.IntegerField(blank=True, db_column='angehaengt_sonst', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='enthalten_in_af',
            field=models.CharField(blank=True, db_column='enthalten_in_af', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='geaendert',
            field=models.IntegerField(blank=True, db_column='geaendert', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='gefunden',
            field=models.IntegerField(blank=True, db_column='gefunden', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='gf',
            field=models.CharField(blank=True, db_column='gf', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='hoechste_kritikalitaet_tf_in_af',
            field=models.CharField(blank=True, db_column='hk_tf_in_af', db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='tf',
            field=models.CharField(blank=True, db_column='tf', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='tf_eigentuemer_org',
            field=models.CharField(blank=True, db_column='tf_eigentuemer_org', db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='tf_technische_plattform',
            field=models.CharField(blank=True, db_column='tf_technische_plattform', db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='userid',
            field=models.CharField(blank=True, db_column='userid', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='vip', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='zufallsgenerator',
            field=models.CharField(blank=True, db_column='zufallsgenerator', db_index=True, max_length=32, null=True),
        ),
    ]
