# Generated by Django 2.2.4 on 2019-09-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0053_auto_20190925_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluebersichtafgfs',
            unique_together={('name_af_neu', 'name_gf_neu'), ('name_gf_neu', 'name_af_neu')},
        ),
    ]
