# Generated by Django 2.2.4 on 2019-09-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0054_auto_20190925_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluebersichtafgfs',
            unique_together={('name_af_neu', 'name_gf_neu')},
        ),
    ]
