# Generated by Django 2.2.4 on 2019-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0055_auto_20190925_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_af_neu',
            field=models.CharField(db_column='name_af_neu', max_length=50, verbose_name='AF Neu'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_gf_neu',
            field=models.CharField(db_column='name_gf_neu', max_length=50, verbose_name='GF Neu'),
        ),
        migrations.AlterUniqueTogether(
            name='tbluebersichtafgfs',
            unique_together={('name_gf_neu', 'name_af_neu'), ('name_af_neu', 'name_gf_neu')},
        ),
    ]
