# Generated by Django 2.2.4 on 2019-09-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0058_auto_20190925_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluebersichtafgfs',
            unique_together={('name_gf_neu', 'name_af_neu'), ('name_af_neu', 'name_gf_neu')},
        ),
    ]
