# Generated by Django 2.2.4 on 2019-09-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0059_auto_20190925_2053'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tblgesamt',
            index_together={('userid_name', 'tf', 'enthalten_in_af', 'plattform', 'gf'), ('modell', 'enthalten_in_af', 'gf')},
        ),
    ]
