# Generated by Django 2.2.4 on 2019-09-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0060_auto_20190925_2056'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tblgesamt',
            index_together={('userid_name', 'tf', 'enthalten_in_af', 'plattform', 'gf', 'vip_kennzeichen', 'zufallsgenerator'), ('gf', 'enthalten_in_af')},
        ),
    ]
