# Generated by Django 2.2.4 on 2019-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0063_auto_20190925_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblracfgruppen',
            name='db2_only',
            field=models.IntegerField(blank=True, db_column='DB2-only', null=True),
        ),
        migrations.AlterField(
            model_name='tblracfgruppen',
            name='produktion',
            field=models.IntegerField(blank=True, db_column='Produktion', null=True),
        ),
        migrations.AlterField(
            model_name='tblracfgruppen',
            name='readonly',
            field=models.IntegerField(blank=True, db_column='Readonly', null=True),
        ),
        migrations.AlterField(
            model_name='tblracfgruppen',
            name='stempel',
            field=models.DateTimeField(db_column='Stempel'),
        ),
        migrations.AlterField(
            model_name='tblracfgruppen',
            name='test',
            field=models.IntegerField(blank=True, db_column='Test', null=True),
        ),
    ]
