# Generated by Django 2.2.4 on 2019-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0064_auto_20190925_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='angehaengt_bekannt',
            field=models.IntegerField(blank=True, db_column='angehaengt_bekannt', null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='angehaengt_sonst',
            field=models.IntegerField(blank=True, db_column='angehaengt_sonst', null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='geaendert',
            field=models.IntegerField(blank=True, db_column='geaendert', null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='gefunden',
            field=models.IntegerField(blank=True, db_column='gefunden', null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='hoechste_kritikalitaet_tf_in_af',
            field=models.CharField(blank=True, db_column='hk_tf_in_af', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='tf_eigentuemer_org',
            field=models.CharField(blank=True, db_column='tf_eigentuemer_org', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='userid',
            field=models.CharField(blank=True, db_column='userid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='vip', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='zufallsgenerator',
            field=models.CharField(blank=True, db_column='zufallsgenerator', max_length=32, null=True),
        ),
    ]
