# Generated by Django 2.2.4 on 2019-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0068_auto_20190925_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racf_rechte',
            options={'managed': True, 'ordering': ['group', 'profil'], 'verbose_name': 'RACF-Rechte', 'verbose_name_plural': '40_RACF - Berechtigungen'},
        ),
        migrations.AlterField(
            model_name='racf_rechte',
            name='group',
            field=models.CharField(max_length=10),
        ),
    ]
