# Generated by Django 2.2.4 on 2019-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0069_auto_20190926_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orga_details',
            name='abteilungsnummer',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orga_details',
            name='fk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orga_details',
            name='orgID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orga_details',
            name='orgaBezeichnung',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orga_details',
            name='organisation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orga_details',
            name='parentOrga',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
