# Generated by Django 2.2.4 on 2019-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0070_auto_20190926_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letzter_import',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Letzter Import', 'verbose_name_plural': 'Letzte Importe'},
        ),
        migrations.AlterModelOptions(
            name='orga_details',
            options={'managed': True, 'ordering': ['organisation', 'orgID', 'parentOrga', 'fkName'], 'verbose_name': 'Orga-Details', 'verbose_name_plural': '50_Orga - Details'},
        ),
        migrations.AlterField(
            model_name='manuelle_berechtigung',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
