# Generated by Django 2.2.4 on 2019-11-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0071_auto_20190926_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrechteneuvonimport',
            name='nachname',
            field=models.CharField(blank=True, db_column='Nachname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteneuvonimport',
            name='vorname',
            field=models.CharField(blank=True, db_column='Vorname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='name',
            field=models.CharField(db_column='name', db_index=True, max_length=191),
        ),
    ]
