# Generated by Django 2.2.4 on 2019-11-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0072_auto_20191109_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qryf3Rechteneuvonimportduplikatfrei',
        ),
    ]
