# Generated by Django 2.2.4 on 2019-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0073_delete_qryf3rechteneuvonimportduplikatfrei'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblgesamt',
            name='af_beschreibung',
            field=models.TextField(blank=True, default='Keine Beschreibung vorhanden', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tblgesamthistorie',
            name='af_beschreibung',
            field=models.TextField(blank=True, default='--', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='hoechste_kritikalitaet_tf_in_af',
            field=models.CharField(blank=True, db_column='hk_tf_in_af', max_length=4, null=True, verbose_name='max. Krit. TF in AF'),
        ),
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='hoechste_kritikalitaet_tf_in_af',
            field=models.CharField(blank=True, db_column='hk_tf_in_af', max_length=4, null=True, verbose_name='max. Krit. TF in AF'),
        ),
    ]
