# Generated by Django 2.2.4 on 2019-11-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0075_auto_20191109_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblgesamthistorie',
            name='vip_kennzeichen',
        ),
        migrations.RemoveField(
            model_name='tblgesamthistorie',
            name='zufallsgenerator',
        ),
        migrations.RemoveField(
            model_name='tblrechteamneu',
            name='vip_kennzeichen',
        ),
        migrations.RemoveField(
            model_name='tblrechteamneu',
            name='zufallsgenerator',
        ),
        migrations.AlterIndexTogether(
            name='tblgesamt',
            index_together={('userid_name', 'tf', 'enthalten_in_af', 'plattform', 'gf'), ('gf', 'enthalten_in_af')},
        ),
        migrations.RemoveField(
            model_name='tblgesamt',
            name='vip_kennzeichen',
        ),
        migrations.RemoveField(
            model_name='tblgesamt',
            name='zufallsgenerator',
        ),
    ]
