# Generated by Django 2.2.4 on 2019-11-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0076_auto_20191109_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblRacfGruppen',
            new_name='kanndaswegTblRacfGruppen',
        ),
    ]
