# Generated by Django 2.2.4 on 2019-11-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0077_auto_20191110_1055'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='racf_rechte',
            index_together={('group', 'profil')},
        ),
    ]
