# Generated by Django 2.2.4 on 2019-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0078_auto_20191113_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamt',
            name='letzte_aenderung',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
