# Generated by Django 2.2.4 on 2019-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0080_auto_20191117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluseridundname',
            name='name',
            field=models.CharField(db_column='name', db_index=True, max_length=191),
        ),
    ]
