# Generated by Django 2.2.4 on 2019-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0082_tblorga_teamliste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblorga',
            options={'managed': True, 'ordering': ['team'], 'verbose_name': 'Orga-Information', 'verbose_name_plural': '06_Team-Übersicht (tblOrga)'},
        ),
        migrations.AddField(
            model_name='tblorga',
            name='freies_team',
            field=models.CharField(blank=True, default=None, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='team',
            field=models.CharField(db_column='team', db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='tblorga',
            unique_together=set(),
        ),
    ]
