# Generated by Django 2.2.4 on 2019-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0084_auto_20191207_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblorga',
            name='freies_team',
            field=models.TextField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='teamliste',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
