# Generated by Django 2.2.4 on 2019-12-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0085_auto_20191207_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserhatrolle',
            name='teamspezifisch',
            field=models.ForeignKey(blank=True, db_column='id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rapp.TblOrga'),
        ),
    ]
