# Generated by Django 2.2.4 on 2019-12-09 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0086_tbluserhatrolle_teamspezifisch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLGruppen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.CharField(max_length=150, unique=True)),
                ('zugriff', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
                ('pfad', models.CharField(max_length=400)),
                ('letzte_aenderung', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ACL-Gruppen',
                'verbose_name_plural': '97_ACL-Gruppen',
                'ordering': ['tf'],
                'managed': True,
            },
        ),
    ]
