# Generated by Django 2.2.4 on 2019-12-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0087_aclgruppen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aclgruppen',
            options={'managed': True, 'ordering': ['tf'], 'verbose_name': 'ACL-Gruppen', 'verbose_name_plural': '95_ACL-Gruppen'},
        ),
    ]
