# Generated by Django 2.2.4 on 2019-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0088_auto_20191209_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclgruppen',
            name='tf',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
