# Generated by Django 2.2.4 on 2020-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0089_auto_20191209_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='letzter_import',
            name='zi_orga',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
