# Generated by Django 3.0.4 on 2020-04-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0092_add_organisation_20200428_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrechteamneu',
            name='npu_grund',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tblrechteamneu',
            name='npu_rolle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tblrechteneuvonimport',
            name='npu_grund',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tblrechteneuvonimport',
            name='npu_rolle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbluseridundname',
            name='npu_grund',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tbluseridundname',
            name='npu_rolle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='orga',
            field=models.ForeignKey(db_column='orga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.TblOrga', verbose_name='Team'),
        ),
    ]
