# Generated by Django 3.0.4 on 2020-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0093_npu_daten_20200429_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrechteamneu',
            name='iiq_organisation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tblrechteneuvonimport',
            name='iiq_organisation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tbluseridundname',
            name='iiq_organisation',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
