# Generated by Django 3.0.4 on 2021-03-14 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0095_auto_20210308_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setze_NPU_namen_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzeige', models.CharField(max_length=200, null=True)),
                ('wert', models.IntegerField(null=True)),
                ('stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'setze_NPU_namen_status',
                'managed': True,
            },
        ),
    ]
