FROM python:3.6

RUN git clone https://github.com/frickler24/RechteDB.git

WORKDIR /RechteDB
# RUN pip install -r requirements/prod.txt

# COPY mariconf.d/ .
# COPY RechteDB/.env RechteDB/.env
# RUN manage.py collectstatic

CMD "gunicorn" "-c" "guniconf.py" "RechteDB.wsgi"

