FROM nginx:latest
RUN apt update && apt upgrade -y && apt install -y curl vim net-tools nmap iputils* 

RUN rm -f /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.not_used
COPY nginx_rapp /etc/nginx/conf.d/rapp.conf

