FROM python:3.6

RUN mkdir -p /RechteDB

COPY requirements /tmp/requirements
RUN pip install -r /tmp/requirements/prod.txt

ADD content.tar.gz /

WORKDIR /RechteDB

CMD "gunicorn" "-c" "guniconf.py" "RechteDB.wsgi"

